version: '3.2'

services:
  ci_cd_blockchain_develop_frontend:
     environment:
       DOCKER_HUB_NAME: "tss45elcity/"
       DOCKER_HUB_REPOSITORY: "repo_1"
       TAG: ":blockchain_develop-frontend_branch_v1"
       FULL_NAME_IMAGE_FOR_DOCKERHUB: $$DOCKER_HUB_NAME$$DOCKER_HUB_REPOSITORY$$TAG
     container_name: test_ci_cd_blockchain_develop-frontend
     image: tss45elcity/repo_1:blockchain_develop-frontend_branch_v1
     ports:
       - "8888:80"
