FROM nginx:latest
COPY frontend/html/index.html /usr/share/nginx/html/index.html
COPY frontend/css/* /usr/share/nginx/html/
COPY frontend/requiments/* /usr/share/nginx/html/
COPY frontend/resources/* /usr/share/nginx/html/
COPY frontend/scripts/* /usr/share/nginx/html/
